### ISSUE TITLE
Help on using setOverlayIcon

### ISSUE THREAD

**Issue by Otiel** [HelgeffegleH/taskbarInterface#1]
I tried using the `setOverlayIcon` function on an existing window, with the following code:

    #w::
        WinGet, handle, ID, A
        tbi := new taskbarInterface(handle)
        tbi.setOverlayIcon(LoadPicture("Shell32.dll","Icon76",isIcon))

I was expecting to see an overlay icon on the active window when I type <kbd>Win</kbd>+<kbd>W</kbd>, but nothing happens. Did I miss something?

When I run the *self_contained_example.ahk* script, I correctly see the window and the overlay icon.

**Comment by HelgeffegleH** [comment]
Hello __Otiel__ :wave: 

The [documentation](https://github.com/HelgeffegleH/taskbarInterface/wiki/Documentation) states tha the application must own the window. This is a limitation of the used [API](https://msdn.microsoft.com/en-us/library/windows/desktop/dd391696(v=vs.85).aspx)

> This handle must belong to a calling process associated with the button's application and must be a valid HWND or the call is ignored.

There are a few exceptions to this rule, but `setOverlayIcon` is not  one of them. You could try [`setTaskbarIcon`](https://github.com/HelgeffegleH/taskbarInterface/wiki/Documentation#icons), it might work depending on how the target window responds to the message. But note that the script is not designed to handle unowned window. If that function works for you and that is all you want to use, I suggest you just send the message yourself, attaching a window to an interface is _overkill_ for that purpose. See [`WM_SETICON`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632643(v=vs.85).aspx).

Thanks for your questions. Good luck.

**Comment by Otiel** [comment]
Hi, thanks for your reply! 😄 

I'm not sure I understand correctly though. When you say "the application must own the window", is the "application" my AutoHotkey script? Or is it the application associated to the handle I retrieve using `WinGet`?

**Comment by HelgeffegleH** [comment]
The  _owning application_ is the application which created the window. Hence, most functions are restricted to be used on windows which you have created in your __script__, for example with `gui, new` in v1 or `guiCreate()` in v2. Meaning, you __cannot__ set an icon overlay on the _calculator_, __not__ even if you `run calc.exe`, beacuse it is the other application which creates the window.

Cheers.

**Comment by Otiel** [comment]
Thanks, that's clear now. :)
